from flask import Flask, request, jsonify
from flask_cors import CORS
import json
import os
import re
import unicodedata
import urllib.request
import urllib.error
import psycopg2
import psycopg2.extras
from datetime import datetime

app = Flask(__name__)
CORS(app)

DATABASE_URL = os.environ.get('DATABASE_URL')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
UMBRAL = 5

# ============================================================
# DICCIONARIO DE CATEGORÍAS — 11 campos semánticos
# ============================================================
CATEGORIAS = {
    'dolor_fisico': {
        'color': '#FF2424',
        'nombre_es': 'dolor físico',
        'nombre_en': 'physical pain',
        'palabras': [
            'dolor','duele','duelen','dolió','doloroso',
            'ardor','arde','ardía','ardió','ardiendo',
            'quema','quemaba','quemar','quemó',
            'abrasó','abrasar','abrasa',
            'escaldó','escaldaba','escaldar',
            'calambre','calambres','cólico','cólicos',
            'contractura','espasmo','espasmos',
            'retorcijón','retorcijones',
            'retorció','retorcía',
            'torció','torcía','torcer','torcimiento',
            'insoportable','adolorida','adolorido',
            'cortar','cortó','cortante','corte',
            'rajar','rajó','rajada','rajadura',
            'pinchar','pinchó','pinchazo','pinchazos',
            'punzada','punzadas','punzante','punzó',
            'clavar','clavó','agujazo',
            'perforar','perforación',
            'atravesar','atravesó',
            'incidir','incisión',
            'lacerante','lacera','laceró',
            'sangrar','sangró','sangrando','sangré',
            'sangre','desangrar','desangrarse','me desangré',
            'hemorragia','hematoma','hematomas',
            'herida','heridas',
            'moretón','moretones',
            'llaga','llagas',
            'lesión','lesiones',
            'magullada','magulladura','amoratada',
            'desgarro','desgarrar','desgarramiento',
            'rasgar','rasgado',
            'tirón','tirones','pellizco','pellizcos',
            'apretó','apretaba','apretar','aprieta',
            'estrujó','estrujaba','estrujar',
            'oprimió','oprimía','oprimir',
            'comprimió','comprimía',
            'quebró','quebraba','quebrar',
            'rompió','rompía',
            'fracturó','fractura','fracturaba',
            'partió','partía',
            'astilló','resquebrajó',
            'pulverizó','pulverizaba','pulverizar',
            'trituró','trituraba','triturar',
            'aplastó','aplastaba','aplastar',
            'destrozó','destrozaba',
            'sufrimiento','sufrir','sufrí',
            'padecimiento','padecer','padecí',
            'agonía','agonizaba',
            'tormento','atormentada','martirio',
            'náuseas','náusea','mareo','mareada',
            'me desmayé','me desvanecí',
            'me descompuse','me descompongo',
            'machucó','machucaba','machuca','tincazo',
            'me mató','me estaba matando',
            'no aguantaba','no aguanté',
            'quedé destrozada','quedé destruida',
            'me dejó cagada','me sacaron la mugre',
            'ardía horrores','horrible dolor',
            'me partió','me rajó',
            'dolores','escozor','picazón','picazon','picor',
            'ardiente','lacerada','lacerado','laceraciones',
            'apuñalada','apuñalado','estocada','puñalada',
            'me retorcía de dolor','contorsión','contorsionaba',
            'malestar físico','malestar fisico',
            'molestia física','molestia fisica',
            'me quejé de dolor','quejido de dolor',
            'tironeo','tironeaba',
            'me sacó un grito','grité de dolor',
            'insufrible','punzadas agudas',
            'hurt','hurts','pain','painful',
            'ache','aching','bleeding','bleed',
            'burning','cramp','wound','cut','bruise',
            'stinging','throbbing','sore','soreness',
            'agony','agonizing','excruciating',
            'tender','tenderness','bruised','bruising',
            'wounded','scraped','scratch','scratching',
            'stab','stabbing','piercing','laceration',
            'discomfort','uncomfortable','unbearable',
            'dolencia','algia','irritación','inflamación','sensibilidad',
            'hipersensibilidad','molestia','presión','compresión','opresión','tensión',
            'tirantez','aguijonazo','latido','palpitación','quemazón','laceración',
            'abrasión','erosión','excoriación','fisura','sangrado','hinchazón','edema',
            'desvanecimiento','desmayo','entumecimiento','adormecimiento','rigidez',
            'fatiga','debilidad','agotamiento','dolor pélvico','dolor vaginal',
            'dolor vulvar','dolor cervical','dolor uterino','dolor abdominal',
            'dolor perineal','dolor mamario','dismenorrea','dispareunia','vulvodinia',
            'vaginismo','neuralgia','hiperalgesia','alodinia','doler','arder','escocer',
            'puncionar','presionar','comprimir','estirar','tironear','raspar',
            'penetrar','lacerar','pellizcar','retorcer','golpear','machucar','romper',
            'partir','destrozar','cuchillo','aguja','clavo','puñal','garfio','tenaza',
            'tornillo','abrelatas','sacacorchos','trituradora','prensa','trampa',
            'mordaza','alambre','espina','astilla','fuego','quemadura','corriente',
            'descarga','latigazo','martillazo','golpe','explosión','ruptura','me dolió',
            'me ardió','me quemó','me pinchó','me cortó','me desgarró','me apretó',
            'me estrujó','me hizo bolsa','me hizo pedazos','me hizo tira',
            'me dejó molida','me dejó machucada','me dejó adolorida',
            'me dejó para la escoba','me dejó destruida','me dejó hecha polvo',
            'vi estrellas','no soportaba','dolía demasiado','dolía a morir',
            'dolía horrores','dolía como el demonio','dolía hasta el alma',
            'sentí que me rompían','sentí que me cortaban','sentí que me atravesaban',
            'sentí que me quemaban','sentí un tirón','sentí un pinchazo',
            'sentí una puntada','sentí un calambre','me corrió un dolor',
            'me dio una puntada','me agarró un dolor','me vino un dolor',
            'quedé doblada','quedé molida','quedé resentida',
            'me dolió más de la cuenta','ailment','algia','irritation','inflammation',
            'sensitivity','hypersensitivity','discomfort','pressure','compression',
            'tightness','tension','sting','throb','throbbing','burning sensation',
            'laceration','abrasion','erosion','excoriation','fissure','bleeding',
            'swelling','edema','fainting','fainting spell','numbness','stiffness',
            'fatigue','weakness','exhaustion','pelvic pain','vaginal pain',
            'vulvar pain','cervical pain','uterine pain','abdominal pain',
            'perineal pain','breast pain','dysmenorrhea','dyspareunia','vulvodynia',
            'vaginismus','neuralgia','hyperalgesia','allodynia','to hurt','to burn',
            'to sting','to puncture','to press','to compress','to stretch','to tug',
            'to scrape','to penetrate','to lacerate','to pinch','to twist','to hit',
            'to bruise','to break','to split','to destroy','knife','needle','nail',
            'dagger','hook','pliers','screw','can opener','corkscrew','crusher','vice',
            'trap','clamp','wire','thorn','splinter','fire','burn','electric current',
            'shock','whiplash','hammer blow','blow','explosion','rupture','it hurt me',
            'it burned me','it pricked me','it cut me','it tore me','it squeezed me',
            'it crushed me','it wrecked me','it tore me apart','it left me wrecked',
            'it left me bruised','it left me sore','it left me destroyed',
            'it left me shattered','i saw stars','i could not stand it',
            'it hurt too much','it hurt like hell','it hurt terribly',
            'it hurt to my core','i felt like i was being broken',
            'i felt like i was being cut','i felt like i was being pierced through',
            'i felt like i was being burned','i felt a pull','i felt a prick',
            'i felt a stabbing pain','i felt a cramp','a pain shot through me',
            'i felt a sharp pain','a pain hit me','a pain came over me',
            'i was left doubled over','i was left wrecked','i was left sore',
            'it hurt more than it should have',
        ]
    },
    'miedo': {
        'color': '#A01F35',
        'nombre_es': 'miedo',
        'nombre_en': 'fear',
        'palabras': [
            'miedo','miedosa',
            'aterrada','aterradora','aterró','aterraba',
            'horror','horrorizada','horrorosa',
            'espanto','espantada','espantosa',
            'fobia','aprensión','aprensiva',
            'pánico','paniqueada',
            'temor','temores','temía','temerosa',
            'ansiedad','ansiosa','ansioso',
            'angustia','angustiada','angustiante',
            'estrés','estresada','estresante',
            'tensión','tensa','tenso',
            'nervios','nerviosa','nervioso','nerviosismo',
            'agitada','agitación',
            'intranquila','intranquilidad',
            'inquieta','inquietud','zozobra',
            'susto','asustada','me asusté',
            'preocupación','preocupada',
            'anticipación','esperar lo peor',
            'taquicardia',
            'temblaba','temblé','temblor',
            'me paralicé','parálisis',
            'me bloqueé','bloqueo',
            'piel de gallina',
            'hiperventilé','respiración agitada',
            'sudor frío','sudorosa',
            'me aferré','me puse rígida',
            'el corazón a mil','me latía fuerte',
            'llorar','lloraba','lloré','llanto','lágrimas',
            'sollozar','sollocé','sollozos',
            'llorosa','quería llorar','ganas de llorar',
            'escalofrío','escalofríos',
            'me cagué de miedo','me cagué',
            'quedé helada','me quedé congelada',
            'me dio cosa','me dio susto',
            'quería salir corriendo','me quería ir',
            'quería escapar','no podía respirar bien',
            'me puse histérica','los nervios a flor de piel',
            'me latía a mil','no podía parar de temblar',
            'temeroso','temerosa','aprensivo',
            'consternada','consternado','consternación',
            'pavor','pavoroso','inseguridad','insegura','inseguro',
            'alarmada','alarmado','alarma','sobresalto',
            'sobresaltada','sobresaltado',
            'me heló la sangre','se me heló la sangre',
            'me quedé sin aire','no podía moverme',
            'quedé paralizada','quedé paralizado',
            'me tiritaba la voz','voz entrecortada','entrecortada',
            'inquietante','desasosiego','desasosegada',
            'recelo','recelosa','desconfianza','desconfiada',
            'fear','anxiety','panic','terror',
            'scared','nervous','dread','worried',
            'frightened','terrified','paralyzed',
            'trembling','shaking',
            'apprehension','apprehensive','uneasy','uneasiness',
            'startled','alarm','alarmed','trembled',
            'freeze','froze','frozen','petrified','dreaded',
            'distress','distressed','jittery',
            'vulnerabilidad','indefensión','impotencia','incertidumbre',
            'hipervigilancia','tiritón','sudoración','palpitaciones','hiperventilación',
            'ahogo','opresión','náusea','mareo','rigidez','congelamiento','tartamudez',
            'sollozo','insomnio','tensión mandibular','respiración entrecortada',
            'voz temblorosa','sequedad bucal','huir','escapar','esconderse','evitar',
            'resistirse','paralizarse','congelarse','bloquearse','aferrarse',
            'encogerse','alejarse','cubrirse','protegerse','callarse','gritar',
            'suplicar','negarse','retroceder','desconectarse','disociarse',
            'me dio miedo','me dio terror','me dio pánico','me dio nervio',
            'me dio julepe','me dio cuco','me aterré','me espanté','quedé congelada',
            'quedé petrificada','quedé tiesa','quedé en blanco','se me apretó el pecho',
            'se me cerró la garganta','se me revolvió la guata',
            'se me aceleró el corazón','me temblaban las piernas','me tiritaba todo',
            'me castañeteaban los dientes','no podía respirar','no podía reaccionar',
            'no sabía qué hacer','quería arrancar','quería irme','quería esconderme',
            'sentí que algo malo pasaría','esperaba lo peor',
            'estaba con los nervios de punta','tenía el corazón a mil',
            'estaba muerta de miedo','estaba cagada de miedo',
            'me entró la desesperación','vulnerability','helplessness','powerlessness',
            'uncertainty','hypervigilance','shivering','sweating','palpitations',
            'hyperventilation','breathlessness','tightness','nausea','dizziness',
            'stiffness','freezing up','stammering','sob','insomnia','jaw tension',
            'shaky breathing','trembling voice','dry mouth','to flee','to escape',
            'to hide','to avoid','to resist','to freeze up','to freeze','to shut down',
            'to cling','to shrink back','to pull away','to cover oneself',
            'to protect oneself','to go silent','to scream','to beg','to refuse',
            'to back away','to zone out','to dissociate','it scared me',
            'it terrified me','it panicked me','it made me nervous','it spooked me',
            'it freaked me out','i was terrified','i was frightened','i was frozen',
            'i was petrified','i went stiff','my mind went blank','my chest tightened',
            'my throat closed up','my stomach turned','my heart raced',
            'my legs were shaking','i was shaking all over','my teeth were chattering',
            'i could not breathe','i could not react','i did not know what to do',
            'i wanted to run off','i wanted to leave','i wanted to hide',
            'i felt something bad was going to happen','i expected the worst',
            'my nerves were on edge','my heart was racing','i was scared to death',
            'i was scared shitless','desperation set in',
        ]
    },
    'verguenza_exposicion': {
        'color': '#C4943D',
        'nombre_es': 'vergüenza / exposición',
        'nombre_en': 'shame / exposure',
        'palabras': [
            'vergüenza','avergonzada','pudor',
            'exposición','expuesta','expuesto',
            'desnudez','desnuda','desnudada',
            'despojada','despojo',
            'íntimo','íntima','intimidad',
            'zona íntima','partes íntimas','lo más íntimo',
            'vulnerable','vulnerabilidad',
            'humillación','humillante',
            'privacidad','privado','privada',
            'observada','observación',
            'pilucha','piluchi',
            'en pelota','encuera','encuerada',
            'mirada','miradas','bajo la lupa',
            'examinada','inspeccionada','inspección',
            'escudriñada','radiografiada','diseccionada',
            'vitrina','escaparate','aparador',
            'exhibida','exhibición',
            'muñeca','maniquí',
            'objeto de estudio','pieza de museo',
            'cosificada','cosificación',
            'deshumanizada','deshumanizante',
            'reducida a un cuerpo','solo un cuerpo',
            'pena','me dio pena','qué pena','penosa',
            'me sonrojé','me puse colorada',
            'degradante','degradada',
            'indigna','indignante',
            'juzgada','juzgar',
            'quería desaparecer',
            'quería que me tragara la tierra',
            'me quería morir de vergüenza',
            'bochorno','bochornoso','turbada','turbado','turbación',
            'sonrojo','sonrojada','sonrojado',
            'ruborizada','ruborizado','rubor',
            'desprotegida','desprotegido','desprotección',
            'indefensa','indefenso','desamparada','desamparo',
            'tratada como objeto','como pieza de carne',
            'trato deshumanizante','sin dignidad',
            'despersonalizada','despersonalizado',
            'cero privacidad','ninguna privacidad','nula privacidad',
            'me sentí un número','me sentí un numero',
            'solo un número','me sentí cosa','como mercancía',
            'shame','ashamed','embarrassed',
            'exposed','naked','vulnerable',
            'humiliation','humiliated',
            'objectified','scrutinized',
            'privacy','intimate',
            'mortified','mortification','blush','blushing',
            'undignified','dehumanizing','dehumanized',
            'stared at','on display','specimen',
            'scrutiny','self-conscious',
            'mortificación','incomodidad','indefensión','degradación','indignidad',
            'deshumanización','despersonalización','objetualización','intimidación',
            'timidez','autoconciencia','inseguridad','inferiorización','semidesnudez',
            'exploración','examinación','escrutinio','vigilancia','intromisión',
            'invasión','descubrimiento','apertura','posicionamiento','litotomía',
            'inmovilización','desvestimiento','exposición genital',
            'exposición corporal','falta de privacidad','pérdida de intimidad',
            'mirada clínica','mirada médica','mirada masculina','mirada institucional',
            'museo','espécimen','muestra','objeto','cosa','mercancía','carne','número',
            'expediente','caso','pieza','cuerpo abierto','cuerpo disponible',
            'cuerpo observado','cuerpo intervenido','cuerpo inspeccionado',
            'cuerpo fragmentado','me dio vergüenza','me dio plancha','me dio pudor',
            'me dio bochorno','me sentí expuesta','me sentí desnuda',
            'me sentí observada','me sentí examinada','me sentí invadida',
            'me sentí vulnerable','me sentí indefensa','me sentí desprotegida',
            'me sentí humillada','me sentí degradada','me sentí juzgada',
            'me sentí como objeto','me sentí como cosa','me sentí como carne',
            'me sentí como mercancía','me sentí como un número','me sentí en vitrina',
            'me sentí bajo la lupa','me sentí reducida a un cuerpo',
            'me sentí tratada como una guagua','me dejaron en pelota',
            'me dejaron pilucha','me hicieron desnudarme','todos podían verme',
            'entraba gente y miraba','no había privacidad','no respetaron mi intimidad',
            'me miraban entre varios','quería taparme','quería vestirme',
            'no sabía dónde mirar','me puse roja','me dio mucha plancha',
            'fue muy incómodo','fue denigrante','fue deshumanizante','mortification',
            'discomfort','helplessness','degradation','indignity','dehumanization',
            'depersonalization','objectification','intimidation','shyness',
            'self-consciousness','insecurity','belittlement','partial nudity',
            'exploration','examination','scrutiny','surveillance','intrusion',
            'invasion','uncovering','opening','positioning','lithotomy position',
            'immobilization','undressing','genital exposure','bodily exposure',
            'lack of privacy','loss of privacy','clinical gaze','medical gaze',
            'male gaze','institutional gaze','museum','specimen','sample','object',
            'thing','merchandise','meat','number','file','case','piece',
            'body laid open','body made available','body under observation',
            'body operated on','body inspected','body fragmented','it embarrassed me',
            'it was so embarrassing','it made me self-conscious','it mortified me',
            'i felt exposed','i felt naked','i felt watched','i felt examined',
            'i felt invaded','i felt vulnerable','i felt defenseless',
            'i felt unprotected','i felt humiliated','i felt degraded','i felt judged',
            'i felt like an object','i felt like a thing','i felt like meat',
            'i felt like merchandise','i felt like a number',
            'i felt like i was on display','i felt under a microscope',
            'i felt reduced to a body','i felt treated like a child',
            'they left me stark naked','they left me stripped bare',
            'they made me undress','everyone could see me',
            'people kept coming in and looking','there was no privacy',
            'my privacy was not respected','several people were looking at me at once',
            'i wanted to cover myself','i wanted to get dressed',
            'i did not know where to look','i turned red','it was mortifying',
            'it was very uncomfortable','it was degrading','it was dehumanizing',
        ]
    },
    'sensaciones_frias': {
        'color': '#2EC4D8',
        'nombre_es': 'sensaciones frías',
        'nombre_en': 'cold sensations',
        'palabras': [
            'frío','fría','frías','fríos',
            'helado','helada','gélido','gélida',
            'congelado','congelante',
            'frialdad','glacial',
            'frío de morgue','frío como el hielo',
            'temperatura helada',
            'me congelé','congelada',
            'me heló','me dejó helada',
            'metal','metálico','metálica',
            'fierro','acero','acero inoxidable',
            'hierro','inoxidable',
            'metalizado','cromado','niquelado',
            'titanio','aluminio',
            'tornillo','corchete','grapa',
            'clavo','alambre','varilla','barra',
            'lámina','placa',
            'quirúrgico','quirúrgica',
            'pabellón','quirófano',
            'plateado','plateada',
            'brillante','liso','lisa','resbaladizo',
            'áspero','áspera','tosco','tosca',
            'duro','dura','dureza',
            'rígido','rígida','rigidez',
            'inerte','inanimado','inanimada',
            'muerto','muerta','sin vida',
            'sin pulso','sin temperatura',
            'cadavérico','cadáver',
            'morgue','frigorífico',
            'disecado','embalsamado','fosilizado',
            'clínico','séptico',
            'antiséptico','aséptico','aséptica',
            'esterilizado','esterilizada','desinfectado',
            'tumba','fosa',
            'cloaca','desagüe','sumidero',
            'humedad','húmedo','húmeda','humedal',
            'congelador','heladera','refrigerador','hielera',
            'témpano','iceberg','glaciar','escarcha',
            'antártida','polo sur','tundra','permafrost',
            'patagonia',
            'llave de tuercas','abrelatas','sacacorchos',
            'pinza','pinzas','tenaza',
            'gancho','garfio',
            'bisturí','tijera','tijeras',
            'cuchillo','cuchilla','espéculo',
            'como una trampa',
            'frío a cagarse','me cagué de frío',
            'me llegó frío hasta los huesos',
            'entumecida','entumecido','entumecimiento',
            'adormecida','adormecido',
            'anestesiada','anestesiado','anestesia local',
            'insensibilizada','distanciamiento','frialdad clínica',
            'cold','freezing','metallic','steel',
            'rigid','icy','frozen','hard',
            'sharp','clinical','sterile',
            'instrument','morgue','cadaver',
            'numb','numbness','sterilized','stainless',
            'chilly','chill','frosty','detached',
            'refrigerado','escarchado','invernal','polar','ártico','antártico',
            'insensible','mojado','cromo','níquel','plata','vidrio','cerámica',
            'plástico','goma fría','superficie lisa','superficie rígida',
            'superficie dura','superficie brillante','superficie pulida','instrumental',
            'máquina','mecanismo','hospital','clínica','consulta','laboratorio',
            'sala blanca','sala estéril','sala vacía','ambiente clínico',
            'ambiente aséptico','luz blanca','luz fluorescente','hielo','nieve',
            'invierno','estatua','piedra','trampa','estaba helado','estaba muy frío',
            'estaba congelado','era un fierro','era puro metal','era frío como hielo',
            'era frío como la muerte','parecía sacado del congelador',
            'parecía de morgue','me congeló','me llegó el frío hasta los huesos',
            'sentí un frío metálico','sentí un fierro helado','sentí el metal',
            'sentí algo muerto','sentí algo sin vida','sentí algo rígido',
            'sentí algo duro','me dio un escalofrío','se me heló el cuerpo',
            'quedé entumecida','era frío e impersonal','era frío y clínico',
            'era como una máquina','era como un abrelatas','era como una tenaza',
            'era como una herramienta','parecía instrumento de tortura','refrigerated',
            'frosted','wintry','polar','arctic','antarctic','numb','wet','chrome',
            'nickel','silver','glass','ceramic','plastic','cold rubber',
            'smooth surface','rigid surface','hard surface','shiny surface',
            'polished surface','instruments','machine','mechanism','hospital','clinic',
            'doctor’s office','laboratory','white room','sterile room','empty room',
            'clinical environment','aseptic environment','white light',
            'fluorescent light','ice','snow','winter','statue','stone','trap',
            'it was freezing','it was very cold','it was frozen','it was cold metal',
            'it was pure metal','it was cold as ice','it was cold as death',
            'it felt like it came out of a freezer','it felt like a morgue',
            'it froze me','the cold went straight to my bones','i felt a metallic cold',
            'i felt icy metal','i felt the metal','it felt lifeless','it felt rigid',
            'it felt hard','it gave me a chill','my whole body went cold',
            'i was left numb','it was cold and impersonal','it was cold and clinical',
            'it was like a machine','it was like a can opener','it was like pliers',
            'it was like a tool','it looked like a torture instrument',
        ]
    },
    'sensaciones_calidas': {
        'color': '#E8935A',
        'nombre_es': 'sensaciones cálidas',
        'nombre_en': 'warm sensations',
        'palabras': [
            'tibio','tibia','tibiecito','tibiecita',
            'templado','templada',
            'calorcito','entibió','entibiando',
            'temperatura agradable',
            'cariño','cariños','cariñoso','cariñosa',
            'amor','amoroso','amorosa',
            'ternura','tierno','tierna',
            'afecto','afectuoso','afectuosa',
            'alegría','alegre','felicidad','feliz',
            'familiar','familiaridad',
            'cercano','cercana','cercanía',
            'vínculo','vinculada',
            'conexión','conectada',
            'cuidado','cuidados','cuidadoso','cuidadosa',
            'empatía','empático','empática',
            'comprensión','comprensivo','comprensiva',
            'considerado','considerada',
            'atento','atenta',
            'amigable','amistoso','amistosa',
            'amable','amabilidad',
            'gentil','gentileza',
            'delicado','delicada','delicadeza',
            'respetuoso','respetuosa','respeto',
            'humano','humana','humanidad',
            'sensible','sensibilidad',
            'acogedor','acogedora','acogida',
            'tranquilidad','tranquila',
            'alivio','aliviada',
            'paz','pacífica',
            'simpático','simpática','buena onda',
            'goma','algodón',
            'tela','tela suave',
            'espuma','esponja','esponjosa','esponjoso',
            'acolchado','acolchada',
            'blando','blanda',
            'suave','suavidad',
            'flexible','maleable',
            'reconfortante','confortable',
            'a gusto','agusto',
            'entrañable','protector','protectora','protección',
            'resguardada','resguardado','resguardo',
            'arropada','arropado','abrazo','abrazada','abrazado',
            'contención emocional','sostén','sostenida','sostenido',
            'acompañada','acompañado','acompañamiento',
            'seguridad emocional',
            'warm','soft','gentle',
            'rubber','cotton',
            'comfortable','soothing','smooth',
            'care','kindness','empathy',
            'warmth','tenderness','affection',
            'nurturing','protective','supportive',
            'embrace','embraced','held','wrapped',
            'cared for','looked after',
            'cálido','caliente','entibiado','atemperado','sedoso','liso','liviano',
            'amortiguado','humectado','lubricado','confianza','atención','contención',
            'seguridad','calma','bienestar','hospitalidad','acompañar','escuchar',
            'explicar','preguntar','avisar','esperar','respetar','contener','calmar',
            'proteger','cubrir','abrigar','sostener','ayudar','validar','reconocer',
            'consolar','tranquilizar','entibiar','lubricar','detenerse','manta',
            'almohada','nube','cobija','nido','refugio','hogar','regazo','mano',
            'caricia','calor','luz','sol','agua tibia','terciopelo','fue muy amorosa',
            'fue muy amoroso','fue muy amable','fue muy cuidadosa','fue muy cuidadoso',
            'fue muy delicada','fue muy delicado','fue muy respetuosa',
            'fue muy respetuoso','fue muy humana','fue muy humano',
            'me trató con cariño','me trató con respeto','me trató con cuidado',
            'me explicó todo','me avisó antes','me pidió permiso',
            'me preguntó si estaba bien','me hizo sentir segura',
            'me hizo sentir tranquila','me hizo sentir acompañada',
            'me hizo sentir contenida','me sentí cuidada','me sentí protegida',
            'me sentí escuchada','me sentí comprendida','me sentí acogida',
            'me sentí en confianza','me dio tranquilidad','me dio calma',
            'me dio confianza','me sostuvo la mano','me habló bonito',
            'me habló con suavidad','se tomó su tiempo','fue buena onda','fue un siete',
            'apenas lo sentí','estaba tibiecito','no fue tan terrible','warm','hot',
            'warmed','tempered','silky','smooth','light','cushioned','moisturized',
            'lubricated','trust','attention','containment','safety','calm','wellbeing',
            'hospitality','to accompany','to listen','to explain','to ask',
            'to give notice','to wait','to respect','to hold','to soothe','to protect',
            'to cover','to keep warm','to help','to validate','to acknowledge',
            'to comfort','to reassure','to warm up','to lubricate','to pause','blanket',
            'pillow','cloud','nest','shelter','home','lap','hand','caress','warmth',
            'sun','warm water','velvet','she was very loving','he was very loving',
            'they were very kind','she was very careful','he was very careful',
            'she was very gentle','he was very gentle','she was very respectful',
            'he was very respectful','she was very humane','he was very humane',
            'they treated me with affection','they treated me with respect',
            'they treated me with care','they explained everything to me',
            'they gave me a heads up','they asked my permission',
            'they asked if i was okay','they made me feel safe',
            'they made me feel calm','they made me feel supported',
            'they made me feel held','i felt cared for','i felt protected',
            'i felt heard','i felt understood','i felt welcomed','i felt at ease',
            'it gave me peace of mind','it calmed me','it gave me confidence',
            'they held my hand','they spoke to me kindly','they spoke to me gently',
            'they took their time','they were really nice','it was great',
            'i barely felt it','it was nice and warm','it was not that bad',
        ]
    },
    'sonido': {
        'color': '#6BBF8A',
        'nombre_es': 'sonido / acústica',
        'nombre_en': 'sound / acoustics',
        'palabras': [
            'sonido','sonidos','ruido','ruidos',
            'chirrido','chirría','chirriar',
            'clic','click',
            'cruje','crujido','crujir',
            'rechinido','rechinar',
            'zumbido','zumba','zumbar',
            'tintineo','tintinear',
            'traqueteo','traquetear',
            'golpeteo','golpe','golpear',
            'martilleo','martillar',
            'repiqueteo','redoble',
            'burbujeo','burbujea',
            'estrépito','estruendo',
            'resonancia','reverberación',
            'vibración','vibra','eco','tictac',
            'murmullo','susurro','rumor','rumores',
            'cuchicheo','parloteo',
            'latido','latidos','palpitación',
            'pulso','pulsación','bombeo',
            'respiración','jadeo',
            'quejido','gemido','gemidos',
            'lamento','lamentos','lamentar','quejumbroso',
            'grito','gritos','gritería','griterío',
            'alarido','alaridos',
            'chillido','chillar',
            'hipido','hipo',
            'sollozos','sollozo',
            'risas','risa','carcajada',
            'bostezo','bostezar',
            'vozarrón','voz grave','voz ronca',
            'ronco','ronca','ronquido','ronquera',
            'carraspeo',
            'silbido','silbar','silba',
            'pitido','pitar','pita',
            'sinfonía','sinfónico',
            'melodía','melódico','melodioso',
            'polifonía','polifónico',
            'armonía','armónico',
            'disonancia','disonante',
            'ritmo','rítmico','compás',
            'nota','notas','tono','tonos',
            'tambor','tamborilleo','percusión',
            'música','musicales','midi',
            'sonido metálico','sonido industrial',
            'sonido de máquina','maquinaria',
            'engranaje','motor','mecanismo',
            'silencio','mutismo',
            'callado','callada','en silencio',
            'nadie habló','no dijo nada',
            'escuché','escuchaba','escuchar',
            'oí','oía','oír',
            'percibí','percibía',
            'retumbaba','resonaba',
            'sonaba feo','sonaba horrible',
            'hacía un ruido','estridente',
            'traqueteando','vibrando','pitido agudo',
            'sonido chirriante','estruendoso','ensordecedor',
            'apagado','amortiguado','sonido sordo','ruido sordo',
            'sound','noise','click','clang','scrape',
            'creak','squeak','rattle',
            'buzz','hum','vibration',
            'silence','heard','listening',
            'muffled','deafening','screeching','beeping',
            'thud','thump','tapping','rustling',
            'chasquido','raspado','fricción','estallido','aspiración','succión',
            'suspiro','llanto','tos','deglución','voz','conversación','orden',
            'pregunta','explicación','advertencia','comentario','broma','regaño','reto',
            'interrupción','agudo','grave','metálico','industrial','mecánico','seco',
            'hueco','sordo','repetitivo','irregular','reverberante','resonante',
            'sonó un clic','sonó un clac','sonó metálico','sonó como máquina',
            'sonó como tijera','sonó como tenaza','sonó como herramienta',
            'sonó horrible','sonó muy fuerte','sonó muy cerca','hizo un ruido',
            'hizo un ruido feo','hizo un ruido seco','hizo un ruido raro',
            'hizo un ruido metálico','chirriaba','crujía','rechinaba','vibraba',
            'zumbaba','me quedó sonando','escuché todo','escuché los instrumentos',
            'escuché a otras personas','escuché comentarios','escuché risas',
            'escuché cuchicheos','nadie decía nada','nadie me hablaba',
            'había un silencio incómodo','el silencio era terrible',
            'solo se escuchaban máquinas','solo se escuchaba mi respiración',
            'solo se escuchaba mi llanto','me pidió que no gritara','me salió un grito',
            'grité de dolor','lloré en silencio','snap','scraping','friction','burst',
            'suction','sigh','crying','cough','swallowing','voice','conversation',
            'order','question','explanation','warning','comment','joke','scolding',
            'reprimand','interruption','high-pitched','low-pitched','metallic',
            'industrial','mechanical','dry','hollow','muffled','repetitive','irregular',
            'reverberating','resonant','there was a click','there was a clack',
            'it sounded metallic','it sounded like a machine',
            'it sounded like scissors','it sounded like pliers',
            'it sounded like a tool','it sounded horrible','it sounded very loud',
            'it sounded very close','it made a sound','it made an ugly sound',
            'it made a dry sound','it made a strange sound','it made a metallic sound',
            'it screeched','it creaked','it grated','it vibrated','it buzzed',
            'it kept echoing in my ears','i heard everything','i heard the instruments',
            'i heard other people','i heard comments','i heard laughter',
            'i heard whispering','no one said anything','no one spoke to me',
            'there was an awkward silence','the silence was terrible',
            'all you could hear were machines','all you could hear was my breathing',
            'all you could hear was my crying','they asked me not to scream',
            'a scream escaped me','i screamed in pain','i cried silently',
        ]
    },
    'aromas': {
        'color': '#E8E0D4',
        'nombre_es': 'aromas / olores',
        'nombre_en': 'aromas / smells',
        'palabras': [
            'olor','olía','huele','huelen','oler',
            'aroma','fragancia',
            'olfato','olfativo',
            'hedor','hediondez','hediondo',
            'pestilencia','fetidez','fétido','fétida',
            'pudredumbre','pudrición','putrefacción',
            'podrido','podredumbre',
            'descompuesto','descomposición',
            'rancio','rancia',
            'corrompido','enmohecido',
            'nauseabundo','nauseabunda',
            'repugnante','repugnancia',
            'asqueroso','asquerosa','asco',
            'maloliente','pestoso',
            'olor característico','olor peculiar',
            'olor raro','olor extraño',
            'mal olor','qué olor','qué peste',
            'huele feo','hedía','apestaba','apeste',
            'olía a','huele a',
            'antiséptico','alcohol','alcohol gel',
            'yodo','cloro','lejía',
            'desinfectante','limpiador',
            'detergente','amoniaco',
            'éter','formol','acetona',
            'químico','química',
            'sintético','sintética',
            'reactivo','laboratorio',
            'sangre','orgánico','sudor',
            'secreción','fluido corporal',
            'fluidos corporales',
            'orina','excremento',
            'vagina','genitales','poto',
            'cochino','cochina','sucio','sucia',
            'alcantarilla','alcantarillado',
            'aguas servidas','desagüe','cañería',
            'perfume','jabón','floral',
            'inodoro','penetrante','acre','rancidez',
            'vaho','tufo','hedores',
            'olor a hospital','olor hospitalario',
            'smell','scent','odor',
            'antiseptic','alcohol','chemical','organic',
            'stench','fragrance','rotten','putrid','sewage',
            'pungent','acrid','musty','reek','reeking',
            'whiff','odorless',
            'etanol','isopropanol','povidona','amoníaco','látex','vinilo','plástico',
            'goma','medicamento','anestésico','hospitalario','farmacéutico','flujo',
            'fluido','menstruación','semen','materia orgánica','humedad','piel','leche',
            'placenta','meconio','moho','acidez','dulzor','amargor','olor penetrante',
            'olor acre','olor metálico','olor rancio','olor orgánico','olor químico',
            'olor estéril','farmacia','baño','cloaca','basura','encierro',
            'olía a hospital','olía a clínica','olía a remedio','olía a desinfectante',
            'olía a alcohol','olía a cloro','olía a yodo','olía a sangre',
            'olía a metal','olía a plástico','olía a goma','olía a baño',
            'olía a humedad','olía a encierro','olía raro','olía extraño','olía fuerte',
            'olía horrible','olía mal','había olor a sangre','había olor químico',
            'había olor a hospital','había un olor penetrante',
            'había un olor desagradable','el olor me dio asco','el olor me mareó',
            'el olor me dio náuseas','sentí olor a limpio','sentí olor a esterilizado',
            'no olía a nada','era un olor difícil de describir',
            'era un olor que quedó en mi memoria','ethanol','isopropanol','povidone',
            'ammonia','latex','vinyl','plastic','rubber','medication','anesthetic',
            'hospital-like','pharmaceutical','discharge','fluid','menstruation','semen',
            'organic matter','humidity','skin','milk','placenta','meconium','mold',
            'acidity','sweetness','bitterness','penetrating smell','acrid smell',
            'metallic smell','rancid smell','organic smell','chemical smell',
            'sterile smell','pharmacy','bathroom','sewer','garbage','confinement',
            'it smelled like a hospital','it smelled like a clinic',
            'it smelled like medicine','it smelled like disinfectant',
            'it smelled like alcohol','it smelled like bleach','it smelled like iodine',
            'it smelled like blood','it smelled like metal','it smelled like plastic',
            'it smelled like rubber','it smelled like a bathroom','it smelled damp',
            'it smelled stuffy','it smelled odd','it smelled strange',
            'it smelled strong','it smelled awful','it smelled bad',
            'there was a smell of blood','there was a chemical smell',
            'there was a hospital smell','there was a penetrating smell',
            'there was an unpleasant smell','the smell disgusted me',
            'the smell made me dizzy','the smell made me nauseous','it smelled clean',
            'it smelled sterilized','it did not smell like anything',
            'it was a smell hard to describe','it was a smell that stayed with me',
        ]
    },
    'violencia_sexual': {
        'color': '#B814E8',
        'nombre_es': 'violencia sexual',
        'nombre_en': 'sexual violence',
        'palabras': [
            'violación','violar','violada',
            'agresión sexual','agresión física',
            'vejación','vejada','vejar',
            'ultraje','ultrajada','ultrajar',
            'atropello','atropellada','violentada',
            'profanación','transgredió','transgresión',
            'sometimiento sexual','sumisión química',
            'coerción sexual','coercitivo',
            'intimidación sexual','intimidación',
            'explotación sexual','estupro',
            'violencia de género',
            'abuso de poder','abuso de confianza',
            'depravado','depravación',
            'lascivo','lascivia','libertinaje',
            'se propasó','se excedió',
            'se aprovechó','abusó de mí',
            'se erectó','erección',
            'se masturbó','masturbación',
            'me penetró','penetración no consentida',
            'abuso sexual','abusada sexualmente',
            'manoseo','manoseada','manosearon',
            'tocamientos no consentidos',
            'tocó donde no debía',
            'tocó más de la cuenta',
            'tocó partes que no debía',
            'entró sin avisar','metió mano',
            'me agarró','me tocó','me manoseó',
            'me palpó sin permiso',
            'hizo algo que no correspondía',
            'me desnudaron innecesariamente',
            'me exhibieron sin necesidad',
            'sin consentimiento','sin mi consentimiento',
            'consentimiento vulnerado',
            'acoso','acosada','acoso sexual',
            'ciberacoso sexual',
            'conducta inapropiada',
            'obsceno','obscena',
            'trauma sexual','traumatizada',
            'victimización','víctima',
            'me pasó a llevar','me faltó el respeto',
            'se mandó un abuso','me vulneró','me hizo algo',
            'violentación','vejatorio','vejatoria',
            'denigrante','denigrada','denigrado',
            'cosificación sexual','violencia obstétrica',
            'maltrato obstétrico','trato denigrante',
            'sin mi permiso','en contra de mi voluntad',
            'contra mi voluntad','me obligaron','me forzaron',
            'forzada','forzado','abuso de autoridad médica',
            'assault','sexual abuse',
            'without consent','harassment',
            'groped','violated','molested',
            'inappropriate contact',
            'non-consensual','coercion',
            'sexual trauma','abuse of power',
            'exploitation','predatory',
            'obstetric violence','forced','forcibly',
            'against my will','degrading',
            'non-consensual touching','misconduct','coerced',
            'sometimiento','violencia ginecológica','violencia médica',
            'violencia institucional','violencia reproductiva','revictimización',
            'abuso de autoridad','conducta sexual inapropiada','contacto no consentido',
            'tocamiento no consentido','procedimiento no consentido',
            'examen no consentido','desacuerdo','negativa','rechazo','coacción',
            'presión','amenaza','manipulación','obligatoriedad','imposición',
            'forzamiento','engaño','incapacidad de consentir',
            'retiro del consentimiento','consentimiento ignorado',
            'ausencia de consentimiento','autonomía vulnerada','límites vulnerados',
            'intimidad vulnerada','palpación innecesaria','exposición innecesaria',
            'desnudamiento forzado','examen invasivo','examen sin explicación',
            'examen bajo coerción','ingreso no autorizado','presencia no autorizada',
            'fotografía no consentida','grabación no consentida','comentario sexual',
            'insinuación sexual','burla sexual','broma sexual','mirada sexualizada',
            'humillación sexual','procedimiento innecesario','exploración innecesaria',
            'contacto prolongado','contacto inapropiado','culpa','asco','confusión',
            'disociación','reviviscencia','evitación','se pasó de la raya',
            'me tocó sin permiso','me tocó donde no debía','me tocó más de la cuenta',
            'me puso las manos encima','me metió mano','me palpó sin avisar',
            'hizo algo innecesario','no me pidió permiso','no me explicó',
            'no me preguntó','ignoró que dije que no','siguió aunque le pedí parar',
            'fue contra mi voluntad','fue sin mi consentimiento','me vulneraron',
            'me pasaron a llevar','me faltaron el respeto','abusaron de su posición',
            'abusaron de su autoridad','me sentí abusada','me sentí violentada',
            'me sentí invadida','me sentí ultrajada','me sentí manoseada',
            'me sentí sexualizada','no pude reaccionar','me quedé paralizada',
            'no supe cómo negarme','pensé que era parte del examen',
            'no sabía que podía decir que no','subjugation','gynecological violence',
            'medical violence','institutional violence','reproductive violence',
            'revictimization','abuse of authority','inappropriate sexual conduct',
            'non-consensual contact','non-consensual touching',
            'non-consensual procedure','non-consensual exam','disagreement','refusal',
            'rejection','coercion','pressure','threat','manipulation','compulsion',
            'imposition','forcing','deception','incapacity to consent',
            'withdrawal of consent','consent ignored','absence of consent',
            'violated autonomy','violated boundaries','violated privacy',
            'unnecessary palpation','unnecessary exposure','forced undressing',
            'invasive exam','exam without explanation','exam under coercion',
            'unauthorized entry','unauthorized presence','non-consensual photography',
            'non-consensual recording','sexual comment','sexual innuendo',
            'sexual mockery','sexual joke','sexualized gaze','sexual humiliation',
            'unnecessary procedure','unnecessary exploration','prolonged contact',
            'inappropriate contact','guilt','disgust','confusion','dissociation',
            'flashback','avoidance','he crossed the line',
            'he touched me without permission','he touched me where he should not have',
            'he touched me more than he should have','he put his hands on me',
            'he groped me','he felt me without warning','he did something unnecessary',
            'he did not ask my permission','he did not explain anything to me',
            'he did not ask me','he ignored that i said no',
            'he kept going even after i asked him to stop','it was against my will',
            'it was without my consent','my rights were violated',
            'they overstepped with me','they disrespected me',
            'they abused their position','they abused their authority','i felt abused',
            'i felt violated','i felt invaded','i felt groped','i felt sexualized',
            'i could not react','i was left paralyzed','i did not know how to refuse',
            'i thought it was part of the exam','i did not know i could say no',
        ]
    },
    'placer_deseo': {
        'color': '#FF2D8A',
        'nombre_es': 'placer / deseo',
        'nombre_en': 'pleasure / desire',
        'palabras': [
            'placer','placentero','placentera',
            'placer sexual','placer corporal','placer físico',
            'goce','gozar','gozosa',
            'orgasmo','orgásmica',
            'erótico','erótica','erotismo',
            'sensual','sensualidad',
            'voluptuoso','voluptuosa',
            'lujuria','lujurioso',
            'excitación sexual','deseo sexual',
            'rico','rica','qué rico',
            'me excitó','me provocó',
            'me gustó el tacto',
            'delicioso','deliciosa',
            'pleasure','pleasurable',
            'orgasm','erotic',
            'sensual','arousal',
            'desire','enjoyment','la pasé bien','fascinada','entretenido','entretenida','me encantó','gozo','amado','amor','maravilloso',
            'complacencia','autoconocimiento','conexión con mi cuerpo',
            'empoderada','empoderado','empoderamiento',
            'disfrute','disfruté','disfrutar',
            'satisfacción','satisfactorio','satisfactoria',
            'libertad corporal','plenitud',
            'satisfaction','satisfying','empowered','empowerment',
            'enjoyed','enjoyable','fulfilling',
            'bodily autonomy','pleasurable experience',
            'bienestar','comodidad','alivio','relajación','calma','suavidad','tibieza',
            'caricia','cosquilleo','estimulación','sensibilidad','excitación',
            'lubricación','pulsación','contracción','expansión','liberación',
            'atracción','libido','fantasía','curiosidad','anticipación','intimidad',
            'conexión','entrega','confianza','apertura','exploración','autoerotismo',
            'masturbación','reciprocidad','juego','seducción','autonomía','libertad',
            'agencia','decisión','elección','presencia','reconocimiento','apropiación',
            'reapropiación','reconexión','descubrimiento','me gustó','lo disfruté',
            'se sintió bien','se sintió rico','fue agradable','fue satisfactorio',
            'fue entretenido','fue bonito','me dio placer','me dio gusto',
            'me produjo cosquillas','me produjo curiosidad','me sentí bien',
            'me sentí cómoda','me sentí relajada','me sentí conectada',
            'me sentí en confianza','me sentí libre','me sentí empoderada',
            'me sentí dueña de mi cuerpo','me reconcilié con mi cuerpo',
            'conocí mejor mi cuerpo','descubrí algo de mí','sentí una conexión',
            'sentí ternura','sentí deseo','sentí excitación','llegué al orgasmo',
            'tuve un orgasmo','me calenté','me prendí','me dio curiosidad',
            'me dieron ganas','fue una experiencia positiva','fue liberador',
            'fue reparador','fue sanador','wellbeing','comfort','relief','relaxation',
            'calm','softness','warmth','caress','tingling','stimulation','sensitivity',
            'arousal','lubrication','pulsing','contraction','expansion','release',
            'attraction','libido','fantasy','curiosity','anticipation','intimacy',
            'connection','surrender','trust','openness','exploration','autoeroticism',
            'masturbation','reciprocity','play','seduction','autonomy','freedom',
            'agency','decision','choice','presence','recognition','reclaiming',
            'reconnection','discovery','i liked it','i enjoyed it','it felt good',
            'it felt great','it was pleasant','it was satisfying','it was fun',
            'it was nice','it gave me pleasure','it pleased me','it tickled',
            'it made me curious','i felt good','i felt comfortable','i felt relaxed',
            'i felt connected','i felt at ease','i felt free','i felt empowered',
            'i felt like i owned my body','i made peace with my body',
            'i got to know my body better','i discovered something about myself',
            'i felt a connection','i felt tenderness','i felt desire','i felt aroused',
            'i reached orgasm','i had an orgasm','i got turned on','i felt like it',
            'it was a positive experience','it was liberating','it was healing',
        ]
    },
    'profesional_hombre': {
        'color': '#4A7BAF',
        'nombre_es': 'profesional hombre',
        'nombre_en': 'male professional',
        'palabras': [
            'médico',
            'ginecólogo','obstetra',
            'urólogo','anestesiólogo',
            'enfermero','radiólogo',
            'interno','becado',
            'técnico','paramédico',
            'matrón','secretario','el tens',
            'especialista hombre',
            'el médico','el doctor',
            'el ginecólogo','el anestesista',
            'facultativo','cirujano','kinesiólogo',
            'male doctor','male physician',
            'male gynecologist','male obstetrician',
            'male nurse','man doctor','he was my doctor',
            'oncólogo','mastólogo','patólogo','sexólogo','fertilólogo','embriólogo',
            'psicólogo','estudiante','perito','médico-legista','camillero',
            'el especialista','el cirujano','el ecografista','el residente',
            'el interno','el becado','el enfermero','el matrón','el técnico',
            'el practicante','el profesional','el examinador','el funcionario',
            'el perito','el doc','el gine','médico hombre','doctor hombre',
            'ginecólogo hombre','el caballero','el señor','el que me atendió',
            'el que me examinó','el que hizo el procedimiento','el que estaba mirando',
            'el que tomó la muestra','el que hizo la eco','el que me operó','el alumno',
            'el joven','profesional masculino','personal masculino','equipo masculino',
            'médico varón','especialista varón','examinador masculino',
            'operador masculino','funcionario masculino','prestador masculino',
            'acompañante masculino','observador masculino','estudiante masculino',
            'student','the male nurse','the male midwife','male doctor',
            'male gynecologist','the gentleman','the man','the young man',
            'male professional','male staff','male team','male physician',
            'male specialist','male examiner','male operator','male staff member',
            'male provider','male companion','male observer','male student'
        ]
    },
    'profesional_mujer': {
        'color': '#F5DD2C',
        'nombre_es': 'profesional mujer',
        'nombre_en': 'female professional',
        'palabras': [
            'médica','doctora',
            'ginecóloga','uróloga',
            'anestesióloga','enfermera',
            'radióloga',
            'interna','becada',
            'paramédica','matrona','partera',
            'doula','dula',
            'secretaria','la tens',
            'especialista mujer',
            'la médica','la medica',
            'la doctora','la ginecóloga',
            'la anestesista',
            'facultativa','cirujana','kinesióloga',
            'female doctor','female physician',
            'female gynecologist','female obstetrician',
            'female nurse','woman doctor','midwife','doula',
            'oncóloga','mastóloga','patóloga','sexóloga','fertilóloga','embrióloga',
            'psicóloga','perita','médica-legista','camillera','la especialista',
            'la cirujana','la ecografista','la residente','la interna','la becada',
            'la enfermera','la matrona','la técnica','la practicante','la profesional',
            'la examinadora','la funcionaria','la perita','la doc','la gine',
            'médica mujer','doctora mujer','ginecóloga mujer','la señora','la señorita',
            'la que me atendió','la que me examinó','la que hizo el procedimiento',
            'la que estaba mirando','la que tomó la muestra','la que hizo la eco',
            'la que me operó','la alumna','la joven','profesional femenina',
            'personal femenino','equipo femenino','examinadora femenina',
            'operadora femenina','funcionaria femenina','prestadora femenina',
            'acompañante femenina','observadora femenina','estudiante femenina',
            'the nurse','the midwife','female doctor','female gynecologist','the woman',
            'the young woman','female professional','female staff','female team',
            'female examiner','female operator','female staff member','female provider',
            'female companion','female observer','female student'
        ]
    },
    'artefactos_procedimientos': {
        'color': '#7C8A99',
        'nombre_es': 'artefactos y procedimientos',
        'nombre_en': 'artifacts and procedures',
        'palabras': [
            'espéculo','valvas','vaginoscopio','colposcopio','histeroscopio',
            'resectoscopio','laparoscopio','ecógrafo','transductor','doppler',
            'mamógrafo','histerómetro','tenáculo','pozzi','museux','foerster','bozeman',
            'cureta','cánula','pipelle','trocar','morcelador','crio-sonda',
            'electrobisturí','láser','aspirador','dilatador','hegar','pratt',
            'amniotomo','citobrush','cervex-brush','espátula de ayre',
            'cepillo endocervical','portaobjetos','hisopo','torunda','sonda uterina',
            'sonda foley','sonda vesical','catéter','jeringa','bisturí','tijera',
            'separador','pinza','suturas','grapas','guantes','lubricante','antiséptico',
            'gel ecográfico','mesa ginecológica','estribos','pierneras','lámpara',
            'biombo','bata','campo quirúrgico','colector','frasco histológico',
            'bolsa de biopsia','formulario clínico','consentimiento informado',
            'instrumental obstétrico','fórceps','ventosa','vacuum',
            'espátulas obstétricas','pelvímetro','fetoscopio','pinard',
            'cardiotocógrafo','tocodinamómetro','monitor fetal','transductor fetal',
            'transductor uterino','doppler fetal','balón cervical','balón de bakri',
            'cinta umbilical','clamp umbilical','bomba de infusión','catéter epidural',
            'aguja espinal','incubadora','cuna térmica','extractor de leche','diu',
            't-cu','t-cu 380a','siu','levonorgestrel','implante','etonogestrel',
            'jadelle','implanon','nexplanon','mirena','kyleena','jaydess','píldora',
            'minipíldora','inyectable','parche','anillo vaginal','preservativo',
            'preservativo interno','diafragma','capuchón cervical',
            'esponja anticonceptiva','espermicida','gel anticonceptivo',
            'anticoncepción de emergencia','levonorgestrel de emergencia','ulipristal',
            'diu de emergencia','toalla higiénica','tampón','copa menstrual',
            'disco menstrual','calzón menstrual','protector diario','aplicador',
            'bolsa térmica','compresa','analgésico','calendario menstrual',
            'termómetro basal','monitor de fertilidad','test de ovulación',
            'test de embarazo','aplicación menstrual','aplicación de fertilidad',
            'pulsera de fertilidad','sensor térmico','entrenador pélvico','biofeedback',
            'electroestimulador','dilatador vaginal','pesario','láser vaginal',
            'radiofrecuencia vaginal','papanicolaou','pap','citología cervical',
            'test de vph','genotipificación','colposcopía','vulvoscopía','vaginoscopía',
            'histeroscopía','histerosalpingografía','hsg','sonohisterografía',
            'histerosonografía','hycosy','ecografía pélvica','ecografía transvaginal',
            'ecografía transabdominal','ecografía mamaria','mamografía','tomosíntesis',
            'resonancia pélvica','tomografía pélvica','biopsia cervical',
            'biopsia endocervical','biopsia endometrial','biopsia vulvar',
            'biopsia vaginal','biopsia mamaria','legrado diagnóstico',
            'pipelle endometrial','conización diagnóstica','laparoscopía diagnóstica',
            'culdocentesis','cistoscopía','urodinamia','examen pélvico',
            'examen bimanual','examen rectovaginal','cultivo vaginal','frotis vaginal',
            'gram vaginal','panel vaginal','pcr genital','beta-hcg','hemograma',
            'perfil hormonal','ca-125','he4','índice roma','tamizaje cervical',
            'tamizaje mamario','tamizaje prenatal','tamizaje genético',
            'tamizaje de its','vacunación vph','consejería anticonceptiva',
            'consejería preconcepcional','autotoma de vph','autoexamen mamario',
            'examen mamario','prueba de vih','prueba de sífilis','prueba de hepatitis',
            'prueba de gonorrea','prueba de clamidia','prueba de tricomoniasis',
            'profilaxis preexposición','prep','profilaxis posexposición','pep',
            'dilatación','curetaje','legrado','aspiración endouterina','ameu',
            'polipectomía','miomectomía','histerectomía','histerectomía total',
            'histerectomía subtotal','histerectomía radical','ablación endometrial',
            'resección endometrial','conización','leep','lletz','crioterapia',
            'termocoagulación','cauterización','vaporización láser',
            'embolización uterina','adhesiolisis','endometriosis-exéresis',
            'quistectomía','destorsión ovárica','salpingostomía','salpingectomía',
            'ooforectomía','salpingooforectomía','fimbrioplastia',
            'reanastomosis tubaria','hidrosálpinx-oclusión','marsupialización',
            'drenaje de bartholin','bartolinectomía','traquelectomía','vulvectomía',
            'vaginectomía','exenteración pélvica','linfadenectomía','ganglio centinela',
            'omentectomía','citorreducción','debulking','braquiterapia','radioterapia',
            'quimioterapia','inmunoterapia','terapia dirigida','hipec',
            'preservación ovárica','transposición ovárica','colporrafia anterior',
            'colporrafia posterior','perineorrafia','perineoplastia','histeropexia',
            'colpopexia','sacrocolpopexia','sacrohisteropexia','fijación sacroespinosa',
            'cabestrillo suburetral','sling','cinta suburetral','tot','tvt',
            'inyección periuretral','neuromodulación','botox vesical',
            'pesario-colocación','pesario-retiro','reparación de fístula',
            'vaginoplastia','labioplastia','himenoplastia','himenotomía','himenectomía',
            'clitoroplastia','capuchoplastia','monsplastia','vulvoplastia',
            'reconstrucción vaginal','reconstrucción vulvar','dilatación vaginal',
            'lipoinyección vulvar','cesárea','parto vaginal','parto instrumental',
            'episiotomía','episiorrafia','reparación perineal','inducción',
            'maduración cervical','amniotomía','amniorrexis','membrane-sweep',
            'oxitocina','misoprostol obstétrico','anestesia epidural',
            'anestesia espinal','anestesia combinada','cerclaje',
            'versión cefálica externa','monitoreo fetal','cardiotocografía',
            'cervicometría','amniocentesis','cordocentesis','biopsia corial',
            'fetoscopía','transfusión intrauterina','reducción multifetal',
            'extracción manual placentaria','revisión uterina','taponamiento uterino',
            'sutura b-lynch','alumbramiento dirigido','kristeller','litotomía',
            'consejería reproductiva','ligadura tubaria','salpingoclasia',
            'salpingectomía anticonceptiva','esterilización','inserción de diu',
            'retiro de diu','recambio de diu','inserción de implante',
            'retiro de implante','recambio de implante','anticoncepción oral',
            'anticoncepción inyectable','anticoncepción transdérmica',
            'anticoncepción vaginal','método de barrera','método del calendario',
            'método sintotérmico','amenorrea de lactancia','coito interrumpido',
            'aborto espontáneo','aborto retenido','aborto incompleto','aborto completo',
            'aborto séptico','aborto recurrente','embarazo anembrionado','muerte fetal',
            'interrupción gestacional','ive','ile','aborto farmacológico',
            'aborto instrumental','dilatación y evacuación','d&e','misoprostol',
            'mifepristona','manejo expectante','evacuación uterina','embarazo ectópico',
            'metotrexato','anamnesis reproductiva','ovulación','foliculometría',
            'recuento folicular','afc','reserva ovárica','amh','fsh','lh','estradiol',
            'progesterona','prolactina','tsh','cariotipo','test poscoital',
            'inducción ovulatoria','estimulación ovárica','estimulación controlada',
            'monitoreo folicular','gatillado ovulatorio','inseminación intrauterina',
            'iiu','inseminación intracervical','inseminación conyugal',
            'inseminación donada','fecundación in vitro','fiv','ivf',
            'punción folicular','aspiración folicular','recuperación ovocitaria','opu',
            'capacitación espermática','fecundación convencional','icsi','imsi','picsi',
            'cultivo embrionario','cocultivo','blastocisto','time-lapse','embryoscope',
            'eclosión asistida','assisted-hatching','biopsia embrionaria','pgt-a',
            'pgt-m','pgt-sr','transferencia embrionaria','transferencia fresca',
            'transferencia congelada','transferencia única','transferencia diferida',
            'criopreservación','vitrificación','desvitrificación','congelación seminal',
            'congelación ovocitaria','congelación embrionaria',
            'criopreservación ovárica','maduración in vitro','ivm',
            'donación ovocitaria','ovodonación','donación seminal',
            'donación embrionaria','embriodonación','banco de gametos',
            'banco de embriones','preservación de fertilidad','oncofertilidad',
            'gestación subrogada','gestación por sustitución','gift','zift',
            'catéter de inseminación','catéter embrionario','aguja de punción',
            'guía ecográfica','micropipeta','micromanipulador','incubadora embrionaria',
            'placa de cultivo','medio de cultivo','pajuelas','criotubos','criotanque',
            'nitrógeno líquido','cámara de recuento','centrífuga',
            'microscopio invertido','láser embrionario','gonadotrofinas','autoinyector',
            'acogida','consentimiento','entrevista clínica','anamnesis','relato',
            'examen físico','examen ginecológico','examen genital',
            'examen proctológico','examen sexológico','peritaje sexológico',
            'peritaje clínico-forense','constatación de lesiones','colposcopía forense',
            'vulvoscopía forense','penescopía','fotografía forense','videocolposcopía',
            'diagrama corporal','registro clínico','documentación','hisopado bucal',
            'hisopado cutáneo','hisopado vaginal','hisopado cervical','hisopado anal',
            'muestra subungueal','raspado subungueal','peinado forense',
            'recolección de vestuario','recolección de fibras',
            'recolección de cabellos','recolección de fluidos','muestra sanguínea',
            'muestra urinaria','muestra de adn','perfil genético','detección de semen',
            'detección espermática','fosfatasa ácida','psa forense','toxicología',
            'alcoholemia','drogas facilitadoras','test de vih','test de sífilis',
            'test de hepatitis','test de gonorrea','test de clamidia',
            'profilaxis de its','profilaxis vih','vacunación hepatitis b',
            'cadena de custodia','nue','rotulado','sellado','embalaje','almacenamiento',
            'traslado','kit de evidencia','set de evidencia','sobre de evidencia',
            'sello de evidencia','formulario pericial','informe médico-legal',
            'prueba de virginidad','prueba de dos dedos','inspección himeneal',
            'certificado de virginidad','esterilización forzada',
            'anticoncepción forzada','embarazo forzado','aborto forzado',
            'examen sin consentimiento','examen bajo anestesia','episiotomía rutinaria',
            'sinfisiotomía','clitoridectomía','infibulación','mutilación genital',
            'virginidad quirúrgica','himenoplastia coercitiva','cesárea coercitiva',
            'separación neonatal','inmovilización obstétrica','rasurado rutinario',
            'enema rutinario','himen','historia ginecológica','aplicación de embarazo',
            'test doméstico','algoritmo de ovulación','ecografía prenatal',
            'fotografía fetal','banco genético','selección embrionaria',
            'diagnóstico preimplantacional','vigilancia gestacional','telemonitoreo',
            'telemedicina ginecológica','autotoma','implante subdérmico',
            'malla pélvica','entrenador vaginal','cirugía íntima',
            'reconstrucción himeneal','partograma','consentimiento obstétrico',
            'ficha perinatal','carné maternal','registro de fertilidad',
            'seguimiento menstrual','wearable reproductivo',
            'inteligencia artificial reproductiva','papo','eco','eco vaginal',
            'eco interna','eco pélvica','test de farmacia','test de orina',
            'examen del vph','biopsia','muestra','cultivo','examen hormonal',
            'conteo de óvulos','pato','camilla','t de cobre','t hormonal',
            'chip anticonceptivo','barrita','condón','forrito','copa','toallita',
            'protector','malla','cinta','pastillas','anticonceptivas','inyección',
            'anillo','día después','pastilla del día después','píldora de emergencia',
            'ligarse','operarse','cortarse las trompas','ponerse la t','sacarse la t',
            'ponerse el implante','sacarse el implante','raspaje','limpieza','vaciado',
            'aspirado','quemado','cono','asa','puntos','reparación','sacar el útero',
            'vaciar el útero','sacar un ovario','sacar las trompas','operar un mioma',
            'sacar un quiste','destapar las trompas','parto normal','parto natural',
            'corte','piquete','epidural','raquídea','goteo','romper la bolsa',
            'despegar membranas','cucharas','monitores','correas','tacto','revisión',
            'tratamiento de fertilidad','inseminación','in vitro','estimulación',
            'hormonas','inyecciones','punción','extracción de óvulos','transferencia',
            'implantación','congelar óvulos','congelar embriones','banco de esperma',
            'donante','vientre de alquiler','vientre subrogado','pérdida',
            'pérdida gestacional','perder el embarazo','perder la guagua',
            'aborto natural','aborto con pastillas','pastillas para abortar',
            'aspiración','interrupción','tres causales','examen médico-legal',
            'constatación','kit de violación','kit forense','hisopado','muestras','adn',
            'examen de virginidad','speculum','vaginal retractor','vaginoscope',
            'colposcope','hysteroscope','resectoscope','laparoscope',
            'ultrasound machine','transducer','doppler','mammography machine',
            'uterine sound','tenaculum','pozzi forceps','museux forceps',
            'foerster forceps','bozeman forceps','curette','cannula','pipelle','trocar',
            'morcellator','cryoprobe','electrocautery','laser','suction device',
            'dilator','hegar dilator','pratt dilator','amniohook','cytobrush',
            'cervex brush','ayre spatula','endocervical brush','microscope slide',
            'swab','cotton ball','uterine catheter','foley catheter','urinary catheter',
            'catheter','syringe','scalpel','scissors','retractor','forceps','sutures',
            'staples','gloves','lubricant','antiseptic','ultrasound gel',
            'gynecological table','stirrups','leg supports','lamp','privacy screen',
            'gown','surgical drape','specimen collector','histology jar','biopsy bag',
            'clinical form','informed consent','obstetric instruments',
            'vacuum extractor','vacuum','obstetric spatulas','pelvimeter','fetoscope',
            'pinard horn','cardiotocograph','tocodynamometer','fetal monitor',
            'fetal transducer','uterine transducer','fetal doppler','cervical balloon',
            'bakri balloon','umbilical tape','umbilical clamp','infusion pump',
            'epidural catheter','spinal needle','incubator','warming bassinet',
            'breast pump','iud','copper t','copper t 380a','ius','levonorgestrel',
            'implant','etonogestrel','jadelle','implanon','nexplanon','mirena',
            'kyleena','jaydess','pill','minipill','injectable','patch','vaginal ring',
            'condom','internal condom','diaphragm','cervical cap',
            'contraceptive sponge','spermicide','contraceptive gel',
            'emergency contraception','emergency levonorgestrel','ulipristal',
            'emergency iud','sanitary pad','tampon','menstrual cup','menstrual disc',
            'period underwear','panty liner','applicator','heating pad','compress',
            'painkiller','period calendar','basal thermometer','fertility monitor',
            'ovulation test','pregnancy test','period tracking app','fertility app',
            'fertility bracelet','thermal sensor','pelvic floor trainer','biofeedback',
            'electrostimulator','vaginal dilator','pessary','vaginal laser',
            'vaginal radiofrequency','pap smear','pap test','cervical cytology',
            'hpv test','genotyping','colposcopy','vulvoscopy','vaginoscopy',
            'hysteroscopy','hysterosalpingography','hsg','sonohysterography',
            'hysterosonography','hycosy','pelvic ultrasound','transvaginal ultrasound',
            'transabdominal ultrasound','breast ultrasound','mammogram','tomosynthesis',
            'pelvic mri','pelvic ct scan','cervical biopsy','endocervical biopsy',
            'endometrial biopsy','vulvar biopsy','vaginal biopsy','breast biopsy',
            'diagnostic curettage','endometrial pipelle','diagnostic conization',
            'diagnostic laparoscopy','culdocentesis','cystoscopy','urodynamics',
            'pelvic exam','bimanual exam','rectovaginal exam','vaginal culture',
            'vaginal smear','vaginal gram stain','vaginal panel','genital pcr test',
            'beta hcg','blood count','hormone panel','ca-125','he4','roma index',
            'cervical screening','breast screening','prenatal screening',
            'genetic screening','sti screening','hpv vaccination',
            'contraceptive counseling','preconception counseling','hpv self-sampling',
            'breast self-exam','breast exam','hiv test','syphilis test',
            'hepatitis test','gonorrhea test','chlamydia test','trichomoniasis test',
            'pre-exposure prophylaxis','prep','post-exposure prophylaxis','pep',
            'dilation','curettage','endouterine aspiration','manual vacuum aspiration',
            'polypectomy','myomectomy','hysterectomy','total hysterectomy',
            'subtotal hysterectomy','radical hysterectomy','endometrial ablation',
            'endometrial resection','conization','leep','lletz','cryotherapy',
            'thermocoagulation','cauterization','laser vaporization',
            'uterine embolization','adhesiolysis','endometriosis excision','cystectomy',
            'ovarian detorsion','salpingostomy','salpingectomy','oophorectomy',
            'salpingo-oophorectomy','fimbrioplasty','tubal reanastomosis',
            'hydrosalpinx occlusion','marsupialization','bartholin gland drainage',
            'bartholinectomy','trachelectomy','vulvectomy','vaginectomy',
            'pelvic exenteration','lymphadenectomy','sentinel node','omentectomy',
            'cytoreduction','debulking','brachytherapy','radiotherapy','chemotherapy',
            'immunotherapy','targeted therapy','hipec','ovarian preservation',
            'ovarian transposition','anterior colporrhaphy','posterior colporrhaphy',
            'perineorrhaphy','perineoplasty','hysteropexy','colpopexy','sacrocolpopexy',
            'sacrohysteropexy','sacrospinous fixation','suburethral sling','sling',
            'suburethral tape','tot','tvt','periurethral injection','neuromodulation',
            'bladder botox','pessary fitting','pessary removal','fistula repair',
            'vaginoplasty','labiaplasty','hymenoplasty','hymenotomy','hymenectomy',
            'clitoroplasty','hood reduction','monsplasty','vulvoplasty',
            'vaginal reconstruction','vulvar reconstruction','vaginal dilation',
            'vulvar fat injection','c-section','vaginal birth','instrumental delivery',
            'episiotomy','episiorrhaphy','perineal repair','induction',
            'cervical ripening','amniotomy','amniorrhexis','membrane sweep','oxytocin',
            'obstetric misoprostol','epidural anesthesia','spinal anesthesia',
            'combined spinal-epidural','cerclage','external cephalic version',
            'fetal monitoring','cardiotocography','cervical length measurement',
            'amniocentesis','cordocentesis','chorionic villus sampling','fetoscopy',
            'intrauterine transfusion','multifetal reduction','manual placenta removal',
            'uterine revision','uterine tamponade','b-lynch suture',
            'active management of the third stage','fundal pressure',
            'lithotomy position','reproductive counseling','tubal ligation',
            'tubal sterilization','contraceptive salpingectomy','sterilization',
            'iud insertion','iud removal','iud replacement','implant insertion',
            'implant removal','implant replacement','oral contraception',
            'injectable contraception','transdermal contraception',
            'vaginal contraception','barrier method','calendar method',
            'symptothermal method','lactational amenorrhea','withdrawal method',
            'miscarriage','missed miscarriage','incomplete miscarriage',
            'complete miscarriage','septic abortion','recurrent miscarriage',
            'anembryonic pregnancy','fetal death','pregnancy termination','ive','ile',
            'medication abortion','surgical abortion','dilation and evacuation','d&e',
            'misoprostol','mifepristone','expectant management','uterine evacuation',
            'ectopic pregnancy','methotrexate','reproductive history','ovulation',
            'follicle tracking','follicle count','antral follicle count',
            'ovarian reserve','amh','fsh','lh','estradiol','progesterone','prolactin',
            'tsh','karyotype','postcoital test','ovulation induction',
            'ovarian stimulation','controlled stimulation','follicle monitoring',
            'trigger shot','intrauterine insemination','iui',
            'intracervical insemination','partner insemination','donor insemination',
            'in vitro fertilization','ivf','follicular puncture',
            'follicular aspiration','egg retrieval','sperm preparation',
            'conventional fertilization','icsi','imsi','picsi','embryo culture',
            'co-culture','blastocyst','time-lapse imaging','embryoscope',
            'assisted hatching','embryo biopsy','pgt-a','pgt-m','pgt-sr',
            'embryo transfer','fresh transfer','frozen transfer',
            'single embryo transfer','deferred transfer','cryopreservation',
            'vitrification','devitrification','sperm freezing','egg freezing',
            'embryo freezing','ovarian tissue cryopreservation','in vitro maturation',
            'ivm','egg donation','sperm donation','embryo donation','gamete bank',
            'embryo bank','fertility preservation','oncofertility','surrogacy','gift',
            'zift','insemination catheter','embryo transfer catheter','puncture needle',
            'ultrasound guidance','micropipette','micromanipulator','embryo incubator',
            'culture dish','culture medium','cryopreservation straws','cryotubes',
            'cryotank','liquid nitrogen','counting chamber','centrifuge',
            'inverted microscope','embryo laser','gonadotropins','autoinjector',
            'intake','consent','clinical interview','medical history','account',
            'physical exam','gynecological exam','genital exam','proctological exam',
            'sexological exam','sexological expert assessment',
            'clinical-forensic assessment','injury documentation','forensic colposcopy',
            'forensic vulvoscopy','penile examination','forensic photography',
            'videocolposcopy','body diagram','clinical record','documentation',
            'oral swab','skin swab','vaginal swab','cervical swab','anal swab',
            'subungual sample','subungual scraping','forensic combing',
            'clothing collection','fiber collection','hair collection',
            'fluid collection','blood sample','urine sample','dna sample',
            'genetic profile','semen detection','sperm detection','acid phosphatase',
            'forensic psa','toxicology','blood alcohol test','date rape drugs',
            'sti prophylaxis','hiv prophylaxis','hepatitis b vaccination',
            'chain of custody','unique event number','labeling','sealing','packaging',
            'storage','transport','evidence kit','evidence set','evidence envelope',
            'evidence seal','forensic report form','medico-legal report',
            'virginity test','two-finger test','hymen inspection',
            'virginity certificate','forced sterilization','forced contraception',
            'forced pregnancy','forced abortion','non-consensual exam',
            'exam under anesthesia','routine episiotomy','symphysiotomy',
            'clitoridectomy','infibulation','genital mutilation','surgical virginity',
            'coercive hymenoplasty','coercive c-section','neonatal separation',
            'obstetric restraint','routine shaving','routine enema','hymen',
            'gynecological history','pregnancy app','home test','ovulation algorithm',
            'prenatal ultrasound','fetal photograph','genetic bank','embryo selection',
            'preimplantation diagnosis','pregnancy monitoring','telemonitoring',
            'gynecological telemedicine','self-sampling','subdermal implant',
            'pelvic mesh','vaginal trainer','intimate surgery','hymen reconstruction',
            'partograph','obstetric consent','perinatal record','maternal health card',
            'fertility log','period tracking','reproductive wearable','reproductive ai',
            'ultrasound','vaginal ultrasound','internal ultrasound','drugstore test',
            'urine test','biopsy','sample','culture test','hormone test','egg count',
            'exam table','hormonal t','contraceptive chip','the rod','rubber','cup',
            'pad','liner','mesh','tape','pills','contraceptives','shot','ring',
            'morning after','morning after pill','emergency pill','get your tubes tied',
            'get operated on','get your tubes cut','get the t put in',
            'get the t taken out','get the implant put in','get the implant taken out',
            'scraping','cleaning','emptying','suctioned','cauterized','cone','loop',
            'stitches','repair','take out the uterus','empty the uterus',
            'take out an ovary','take out the tubes','operate on a fibroid',
            'take out a cyst','unblock the tubes','normal delivery','natural birth',
            'cut','jab','epidural','spinal','drip','break the water','monitors',
            'straps','vaginal exam','check','fertility treatment','insemination',
            'in vitro','stimulation','hormones','injections','puncture','transfer',
            'implantation','freeze eggs','freeze embryos','sperm bank','donor',
            'surrogate womb','loss','pregnancy loss','lose the pregnancy',
            'lose the baby','natural miscarriage','pill abortion','abortion pills',
            'aspiration','termination','three grounds law','medico-legal exam',
            'rape kit','forensic kit','swabbing','samples','dna','virginity exam'
        ]
    }
}

# ============================================================
# NORMALIZACIÓN DE TILDES
# El corpus llega con ortografía inconsistente: mismo hablante puede
# escribir "dolió" o "dolio", "vergüenza" o "verguenza". Sin esto,
# el clasificador solo detecta la forma exacta que quedó tipeada en
# el diccionario, y pierde todas las variantes sin tilde.
# Se normaliza tanto el texto del relato como cada palabra del
# diccionario antes de comparar, así ambos quedan en el mismo
# alfabeto y coinciden sin importar si el relato llevaba tildes.
# La ñ se protege explícitamente: NFKD la descompone en "n" + tilde
# combinante, y removerla la convertiría en "n" común, lo cual es un
# error de fondo (año / ano son palabras distintas, no una acentuada
# y otra no).
# ============================================================
def quitar_tildes(texto):
    texto = texto.replace('ñ', '\x00').replace('Ñ', '\x01')
    descompuesto = unicodedata.normalize('NFKD', texto)
    sin_tildes = ''.join(c for c in descompuesto if not unicodedata.combining(c))
    return sin_tildes.replace('\x00', 'ñ').replace('\x01', 'Ñ')

# Patrones precompilados por categoría, calculados una sola vez al
# iniciar el servidor. Cada palabra del diccionario se normaliza y
# se compila con límite de palabra, para no volver a hacerlo en cada
# relato que llega por el webhook.
_PATRONES_CATEGORIA = {
    cat: [
        re.compile(r'(?<!\w)' + re.escape(quitar_tildes(palabra.lower())) + r'(?!\w)')
        for palabra in datos['palabras']
    ]
    for cat, datos in CATEGORIAS.items()
}

# ============================================================
# BASE DE DATOS
# ============================================================
def get_conn():
    return psycopg2.connect(DATABASE_URL, sslmode='require')

def init_db():
    conn = get_conn()
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS respuestas (
        id SERIAL PRIMARY KEY,
        timestamp TEXT,
        relato TEXT,
        relato_traducido TEXT,
        correo TEXT,
        idioma TEXT,
        categorias_activadas TEXT,
        intensidades TEXT
    )''')
    c.execute('''ALTER TABLE respuestas
        ADD COLUMN IF NOT EXISTS relato_traducido TEXT''')
    c.execute('''CREATE TABLE IF NOT EXISTS pintitas (
        id SERIAL PRIMARY KEY,
        respuesta_id INTEGER,
        categoria TEXT,
        intensidad REAL,
        timestamp TEXT
    )''')
    conn.commit()
    conn.close()

with app.app_context():
    init_db()

# ============================================================
# TRADUCCIÓN
# ============================================================
def traducir_relato(texto):
    if not ANTHROPIC_API_KEY:
        return None
    try:
        payload = json.dumps({
            'model': 'claude-haiku-4-5-20251001',
            'max_tokens': 1000,
            'messages': [{
                'role': 'user',
                'content': (
                    'Traduce al español este relato de experiencia corporal. '
                    'Mantén el tono íntimo y personal. '
                    'Solo responde con la traducción, sin comentarios adicionales:\n\n'
                    + texto
                )
            }]
        }).encode('utf-8')
        req = urllib.request.Request(
            'https://api.anthropic.com/v1/messages',
            data=payload,
            headers={
                'x-api-key': ANTHROPIC_API_KEY,
                'anthropic-version': '2023-06-01',
                'content-type': 'application/json'
            }
        )
        with urllib.request.urlopen(req, timeout=30) as response:
            data = json.loads(response.read())
            return data['content'][0]['text']
    except Exception:
        return None

# ============================================================
# ANÁLISIS SEMÁNTICO
# ============================================================
def analizar_relato(texto):
    texto_normalizado = quitar_tildes(texto.lower())
    resultado = {}
    for cat, patrones in _PATRONES_CATEGORIA.items():
        menciones = sum(1 for patron in patrones if patron.search(texto_normalizado))
        if menciones > 0:
            palabras_texto = max(1, len(texto.split()))
            intensidad = min(1.0, menciones / max(1, palabras_texto / 20))
            resultado[cat] = round(intensidad, 3)
    return resultado

def detectar_idioma(texto):
    palabras_es = ['que','con','una','por','para','como','pero','los','las','del']
    palabras_en = ['the','and','that','with','for','this','but','are','was','have']
    score_es = sum(1 for p in palabras_es if f' {p} ' in f' {texto.lower()} ')
    score_en = sum(1 for p in palabras_en if f' {p} ' in f' {texto.lower()} ')
    return 'es' if score_es >= score_en else 'en'

# ============================================================
# GUARDAR
# ============================================================
def guardar_respuesta(relato, correo, categorias_activadas):
    conn = get_conn()
    c = conn.cursor()
    idioma = detectar_idioma(relato)
    relato_traducido = traducir_relato(relato) if idioma == 'en' else None
    c.execute('''INSERT INTO respuestas
        (timestamp, relato, relato_traducido, correo, idioma, categorias_activadas, intensidades)
        VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING id''',
        (datetime.now().isoformat(),
         relato,
         relato_traducido,
         correo,
         idioma,
         json.dumps(list(categorias_activadas.keys())),
         json.dumps(categorias_activadas)))
    respuesta_id = c.fetchone()[0]
    for cat, intensidad in categorias_activadas.items():
        c.execute('''INSERT INTO pintitas
            (respuesta_id, categoria, intensidad, timestamp)
            VALUES (%s,%s,%s,%s)''',
            (respuesta_id, cat, intensidad, datetime.now().isoformat()))
    conn.commit()
    c.execute('SELECT COUNT(*) FROM respuestas')
    n = c.fetchone()[0]
    conn.close()
    return respuesta_id, n

# ============================================================
# ENDPOINTS
# ============================================================
@app.route('/webhook', methods=['POST'])
def webhook():
    datos = request.json or {}
    relato = ''
    correo = ''

    if 'data' in datos:
        for field in datos.get('data', {}).get('fields', []):
            if field.get('type') == 'TEXTAREA':
                relato = field.get('value', '')
            if field.get('type') == 'INPUT_EMAIL':
                correo = field.get('value', '')

    if not relato:
        relato = datos.get('relato', datos.get('texto', datos.get('story', '')))
    if not correo:
        correo = datos.get('correo', datos.get('email', ''))

    if not relato:
        return jsonify({'status': 'error', 'mensaje': 'sin relato'}), 400

    categorias = analizar_relato(relato)
    respuesta_id, n_total = guardar_respuesta(relato, correo, categorias)

    return jsonify({
        'status': 'ok',
        'id': respuesta_id,
        'total_respuestas': n_total,
        'categorias_activadas': categorias,
        'nueva_sintesis': n_total % UMBRAL == 0
    })

@app.route('/estado', methods=['GET'])
def estado():
    conn = get_conn()
    c = conn.cursor()
    c.execute('SELECT COUNT(*) FROM respuestas')
    n_respuestas = c.fetchone()[0]
    c.execute(
        'SELECT categoria, COUNT(*) as n, AVG(intensidad) as avg_int '
        'FROM pintitas GROUP BY categoria ORDER BY n DESC'
    )
    pintitas = c.fetchall()
    conn.close()

    datos_pintitas = [{
        'categoria': p[0],
        'cantidad': p[1],
        'intensidad_promedio': round(p[2], 3),
        'color': CATEGORIAS.get(p[0], {}).get('color', '#888'),
        'nombre_es': CATEGORIAS.get(p[0], {}).get('nombre_es', p[0]),
        'nombre_en': CATEGORIAS.get(p[0], {}).get('nombre_en', p[0])
    } for p in pintitas]

    return jsonify({
        'total_respuestas': n_respuestas,
        'pintitas': datos_pintitas
    })

@app.route('/pintitas_recientes', methods=['GET'])
def pintitas_recientes():
    n = int(request.args.get('n', 20))
    conn = get_conn()
    c = conn.cursor()
    c.execute(
        'SELECT id, respuesta_id, categoria, intensidad, timestamp '
        'FROM pintitas ORDER BY id DESC LIMIT %s', (n,)
    )
    rows = c.fetchall()
    conn.close()
    return jsonify([{
        'id': r[0],
        'respuesta_id': r[1],
        'categoria': r[2],
        'intensidad': r[3],
        'color': CATEGORIAS.get(r[2], {}).get('color', '#888'),
        'nombre_es': CATEGORIAS.get(r[2], {}).get('nombre_es', r[2]),
        'timestamp': r[4]
    } for r in rows])

@app.route('/relato/<int:respuesta_id>', methods=['GET'])
def obtener_relato(respuesta_id):
    conn = get_conn()
    c = conn.cursor()
    c.execute(
        'SELECT relato, relato_traducido, idioma, categorias_activadas, intensidades, timestamp '
        'FROM respuestas WHERE id = %s', (respuesta_id,)
    )
    row = c.fetchone()
    conn.close()
    if not row:
        return jsonify({'error': 'no encontrado'}), 404
    return jsonify({
        'id': respuesta_id,
        'relato': row[0],
        'relato_traducido': row[1],
        'idioma': row[2],
        'categorias_activadas': json.loads(row[3]),
        'intensidades': json.loads(row[4]),
        'timestamp': row[5]
    })

@app.route('/cargar_corpus', methods=['POST'])
def cargar_corpus():
    datos = request.json or []
    cargados = 0
    for r in datos:
        relato = r.get('relato_experiencia', r.get('relato', ''))
        correo = r.get('correo', r.get('email', ''))
        if relato:
            categorias = analizar_relato(relato)
            guardar_respuesta(relato, correo, categorias)
            cargados += 1
    return jsonify({'status': 'ok', 'cargados': cargados})

@app.route('/reiniciar', methods=['POST'])
def reiniciar():
    conn = get_conn()
    c = conn.cursor()
    c.execute('DELETE FROM respuestas')
    c.execute('DELETE FROM pintitas')
    conn.commit()
    conn.close()
    return jsonify({'status': 'ok', 'mensaje': 'corpus reiniciado'})

if __name__ == '__main__':
    print('Servidor Espéculo(ar) — 11 categorías')
    app.run(debug=True, port=5000)
